language: python

notifications:
  email: true

virtualenv:
  system_site_packages: true

python:
  - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - sudo apt-get install python-scipy
    - sudo apt-get build-dep python-scipy
    - pip install cython 

install:
    - pip install -r requirements.txt

script: "nosetests"
