#
#GENERAL SETTINGS
roi_files: "pipeline/rois/{roi_id}.nii*"
sub_folder: subjects

#GROUP SETTINGS
rois:


conds:
    wordscram:
        base_dir: 'pipeline/subjects'
        nii_files: "{sub_id}/short_wordscram/*nii*"
        audio_env: "aud_env_wordscram.npy"
        prop_pass_thresh: .70
        notes: "Pieman story scrambled at the word level"
        
        offset: 10
        max_len: 280
        threshold: 6000
        #groups: csv file putting participants into groups...

    wordscram2:
        base_dir: 'pipeline/subjects'
        nii_files: "{sub_id}/short_wordscram/*nii*"
        audio_env: "aud_env_wordscram.npy"
        prop_pass_thresh: .70
        notes: "Pieman story scrambled at the word level"
        
        offset: 10
        max_len: 280
        threshold: 6000
