#
#GENERAL SETTINGS
roi_files: "pipeline/rois/{roi_id}.nii*"
sub_folder: subjects

#GROUP SETTINGS
rois:


conds:
    test_cond:
        base_dir: 'pipeline/subjects'
        nii_files: 'test_sub{sub_id}.npy'
        audio_env:
        prop_pass_thresh: .7
        notes: "test data"
        run: 'test_cond'

        offset: 0
        max_len: 10
        threshold: 6000
