#
#GENERAL SETTINGS
roi_files: "tests/data/fullpipe/rois/{roi_id}.nii*"
sub_folder: subjects

#GROUP SETTINGS
rois:


conds:
    wordscram:
        base_dir: 'tests/data/fullpipe/subjects'
        nii_files: "{sub_id}/short_wordscram/*nii*"
        audio_env: "aud_env_wordscram.npy"
        prop_pass_thresh: .70
        notes: "Pieman story scrambled at the word level"
        
        offset: 10
        max_len: 280
        threshold: 6000

    wordscram2:
        base_dir: 'tests/data/fullpipe/subjects'
        nii_files: "{sub_id}/short_wordscram/*nii*"
        audio_env: "aud_env_wordscram.npy"
        prop_pass_thresh: .70
        notes: "Pieman story scrambled at the word level"
        
        offset: 10
        max_len: 280
        threshold: 6000
