#
#GENERAL SETTINGS
roi_files: "pycorr_full_data/rois/{roi_id}.nii*"     # where to load roi files from
sub_folder: subjects                                 # where to save subject data

#GROUP SETTINGS
rois:

# DEFAULT SETTINGS FOR CONDITIONS
# (notice that some YAML magic is used to add defaults to all conditions)
default: &default
    base_dir: 'pycorr_full_data/subjects'
    audio_env: "aud_env_wordscram.npy"
    prop_pass_thresh: .70
    offset: 10
    max_len: 280
    threshold: 6000
    
conds:
    wordscram:
        # Add defaults
        <<: *default
        # Condition specific settings
        nii_files: "{sub_id}/short_wordscram/*nii*"
        notes: "Pieman story scrambled at the word level"
        run: "wordscram"

    wordscram2:
        <<: *default
        # Note that wordscram2 uses the same niftis as the previous condition
        nii_files: "{sub_id}/short_wordscram/*nii*"
        notes: "Pieman story scrambled at the word level"
        run: "wordscram2"

    intact:
        <<: *default
        nii_files: "{sub_id}/intact/*nii*"
        notes: "Pieman story in it's sequential glory"
        run: "intact"
